version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 18
    commands:
      - 'yarn install'
  build:
    commands:
      - 'yarn build'
  post_build:
    commands:
      - 'yarn test:unit --runInBand'
