version: '3.1'

services:
  db:
    image: postgres:14.2
    restart: always
    ports:
      - '5432:5432'
    environment:
      POSTGRES_PASSWORD: foobar88

  redis:
    build:
      context: .dockerfiles
      dockerfile: redis.Dockerfile
      args:
        - REDIS_USER=gitpoap-redis
        - REDIS_PASSWORD=ICanHazASecurePassword
    ports:
      - '6379:6379'

  fake-poap-auth:
    build:
      context: .
      dockerfile: .dockerfiles/fake-poap-auth/auth.Dockerfile
    ports:
      - '4005:4005'
    environment:
      - POAP_CLIENT_ID=a good client id
      - POAP_CLIENT_SECRET=super secret!

  fake-poap-api:
    build:
      context: .
      dockerfile: .dockerfiles/fake-poap-api/api.Dockerfile
    ports:
      - '4004:4004'
    depends_on:
      - fake-poap-auth

  server:
    build:
      context: .
      dockerfile: .dockerfiles/server.Dockerfile
    ports:
      - '3001:3001'
      - '8080:8080'
    depends_on:
      - db
      - redis
      - fake-poap-api
      - fake-poap-auth
    environment:
      - POAP_CLIENT_ID=a good client id
      - POAP_CLIENT_SECRET=super secret!

  prometheus:
    build:
      context: .
      dockerfile: .dockerfiles/prometheus.Dockerfile
    ports:
      - '9090:9090'
    depends_on:
      - db
      - redis
      - fake-poap-api
      - fake-poap-auth
      - server

  grafana:
    build:
      context: .dockerfiles
      dockerfile: grafana.Dockerfile
    ports:
      - '9091:9091'
    depends_on:
      - prometheus
