version: '3.1'

services:
  db:
    image: postgres
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: foobar88

  server:
    build:
      context: .
      dockerfile: .dockerfiles/server.Dockerfile
    ports:
      - "3001:3001"
    depends_on:
      - db
