type Query {
  claim(where: ClaimWhereUniqueInput!): Claim
  findFirstClaim(
    where: ClaimWhereInput
    orderBy: [ClaimOrderByWithRelationInput!]
    cursor: ClaimWhereUniqueInput
    take: Int
    skip: Int
    distinct: [ClaimScalarFieldEnum!]
  ): Claim
  claims(
    where: ClaimWhereInput
    orderBy: [ClaimOrderByWithRelationInput!]
    cursor: ClaimWhereUniqueInput
    take: Int
    skip: Int
    distinct: [ClaimScalarFieldEnum!]
  ): [Claim!]!
  aggregateClaim(
    where: ClaimWhereInput
    orderBy: [ClaimOrderByWithRelationInput!]
    cursor: ClaimWhereUniqueInput
    take: Int
    skip: Int
  ): AggregateClaim!
  groupByClaim(
    where: ClaimWhereInput
    orderBy: [ClaimOrderByWithAggregationInput!]
    by: [ClaimScalarFieldEnum!]!
    having: ClaimScalarWhereWithAggregatesInput
    take: Int
    skip: Int
  ): [ClaimGroupBy!]!
  featuredPOAP(where: FeaturedPOAPWhereUniqueInput!): FeaturedPOAP
  findFirstFeaturedPOAP(
    where: FeaturedPOAPWhereInput
    orderBy: [FeaturedPOAPOrderByWithRelationInput!]
    cursor: FeaturedPOAPWhereUniqueInput
    take: Int
    skip: Int
    distinct: [FeaturedPOAPScalarFieldEnum!]
  ): FeaturedPOAP
  featuredPOAPS(
    where: FeaturedPOAPWhereInput
    orderBy: [FeaturedPOAPOrderByWithRelationInput!]
    cursor: FeaturedPOAPWhereUniqueInput
    take: Int
    skip: Int
    distinct: [FeaturedPOAPScalarFieldEnum!]
  ): [FeaturedPOAP!]!
  aggregateFeaturedPOAP(
    where: FeaturedPOAPWhereInput
    orderBy: [FeaturedPOAPOrderByWithRelationInput!]
    cursor: FeaturedPOAPWhereUniqueInput
    take: Int
    skip: Int
  ): AggregateFeaturedPOAP!
  groupByFeaturedPOAP(
    where: FeaturedPOAPWhereInput
    orderBy: [FeaturedPOAPOrderByWithAggregationInput!]
    by: [FeaturedPOAPScalarFieldEnum!]!
    having: FeaturedPOAPScalarWhereWithAggregatesInput
    take: Int
    skip: Int
  ): [FeaturedPOAPGroupBy!]!
  gitPOAP(where: GitPOAPWhereUniqueInput!): GitPOAP
  findFirstGitPOAP(
    where: GitPOAPWhereInput
    orderBy: [GitPOAPOrderByWithRelationInput!]
    cursor: GitPOAPWhereUniqueInput
    take: Int
    skip: Int
    distinct: [GitPOAPScalarFieldEnum!]
  ): GitPOAP
  gitPOAPS(
    where: GitPOAPWhereInput
    orderBy: [GitPOAPOrderByWithRelationInput!]
    cursor: GitPOAPWhereUniqueInput
    take: Int
    skip: Int
    distinct: [GitPOAPScalarFieldEnum!]
  ): [GitPOAP!]!
  aggregateGitPOAP(
    where: GitPOAPWhereInput
    orderBy: [GitPOAPOrderByWithRelationInput!]
    cursor: GitPOAPWhereUniqueInput
    take: Int
    skip: Int
  ): AggregateGitPOAP!
  groupByGitPOAP(
    where: GitPOAPWhereInput
    orderBy: [GitPOAPOrderByWithAggregationInput!]
    by: [GitPOAPScalarFieldEnum!]!
    having: GitPOAPScalarWhereWithAggregatesInput
    take: Int
    skip: Int
  ): [GitPOAPGroupBy!]!
  githubPullRequest(
    where: GithubPullRequestWhereUniqueInput!
  ): GithubPullRequest
  findFirstGithubPullRequest(
    where: GithubPullRequestWhereInput
    orderBy: [GithubPullRequestOrderByWithRelationInput!]
    cursor: GithubPullRequestWhereUniqueInput
    take: Int
    skip: Int
    distinct: [GithubPullRequestScalarFieldEnum!]
  ): GithubPullRequest
  githubPullRequests(
    where: GithubPullRequestWhereInput
    orderBy: [GithubPullRequestOrderByWithRelationInput!]
    cursor: GithubPullRequestWhereUniqueInput
    take: Int
    skip: Int
    distinct: [GithubPullRequestScalarFieldEnum!]
  ): [GithubPullRequest!]!
  aggregateGithubPullRequest(
    where: GithubPullRequestWhereInput
    orderBy: [GithubPullRequestOrderByWithRelationInput!]
    cursor: GithubPullRequestWhereUniqueInput
    take: Int
    skip: Int
  ): AggregateGithubPullRequest!
  groupByGithubPullRequest(
    where: GithubPullRequestWhereInput
    orderBy: [GithubPullRequestOrderByWithAggregationInput!]
    by: [GithubPullRequestScalarFieldEnum!]!
    having: GithubPullRequestScalarWhereWithAggregatesInput
    take: Int
    skip: Int
  ): [GithubPullRequestGroupBy!]!
  organization(where: OrganizationWhereUniqueInput!): Organization
  findFirstOrganization(
    where: OrganizationWhereInput
    orderBy: [OrganizationOrderByWithRelationInput!]
    cursor: OrganizationWhereUniqueInput
    take: Int
    skip: Int
    distinct: [OrganizationScalarFieldEnum!]
  ): Organization
  organizations(
    where: OrganizationWhereInput
    orderBy: [OrganizationOrderByWithRelationInput!]
    cursor: OrganizationWhereUniqueInput
    take: Int
    skip: Int
    distinct: [OrganizationScalarFieldEnum!]
  ): [Organization!]!
  aggregateOrganization(
    where: OrganizationWhereInput
    orderBy: [OrganizationOrderByWithRelationInput!]
    cursor: OrganizationWhereUniqueInput
    take: Int
    skip: Int
  ): AggregateOrganization!
  groupByOrganization(
    where: OrganizationWhereInput
    orderBy: [OrganizationOrderByWithAggregationInput!]
    by: [OrganizationScalarFieldEnum!]!
    having: OrganizationScalarWhereWithAggregatesInput
    take: Int
    skip: Int
  ): [OrganizationGroupBy!]!
  profile(where: ProfileWhereUniqueInput!): Profile
  findFirstProfile(
    where: ProfileWhereInput
    orderBy: [ProfileOrderByWithRelationInput!]
    cursor: ProfileWhereUniqueInput
    take: Int
    skip: Int
    distinct: [ProfileScalarFieldEnum!]
  ): Profile
  profiles(
    where: ProfileWhereInput
    orderBy: [ProfileOrderByWithRelationInput!]
    cursor: ProfileWhereUniqueInput
    take: Int
    skip: Int
    distinct: [ProfileScalarFieldEnum!]
  ): [Profile!]!
  aggregateProfile(
    where: ProfileWhereInput
    orderBy: [ProfileOrderByWithRelationInput!]
    cursor: ProfileWhereUniqueInput
    take: Int
    skip: Int
  ): AggregateProfile!
  groupByProfile(
    where: ProfileWhereInput
    orderBy: [ProfileOrderByWithAggregationInput!]
    by: [ProfileScalarFieldEnum!]!
    having: ProfileScalarWhereWithAggregatesInput
    take: Int
    skip: Int
  ): [ProfileGroupBy!]!
  project(where: ProjectWhereUniqueInput!): Project
  findFirstProject(
    where: ProjectWhereInput
    orderBy: [ProjectOrderByWithRelationInput!]
    cursor: ProjectWhereUniqueInput
    take: Int
    skip: Int
    distinct: [ProjectScalarFieldEnum!]
  ): Project
  projects(
    where: ProjectWhereInput
    orderBy: [ProjectOrderByWithRelationInput!]
    cursor: ProjectWhereUniqueInput
    take: Int
    skip: Int
    distinct: [ProjectScalarFieldEnum!]
  ): [Project!]!
  aggregateProject(
    where: ProjectWhereInput
    orderBy: [ProjectOrderByWithRelationInput!]
    cursor: ProjectWhereUniqueInput
    take: Int
    skip: Int
  ): AggregateProject!
  groupByProject(
    where: ProjectWhereInput
    orderBy: [ProjectOrderByWithAggregationInput!]
    by: [ProjectScalarFieldEnum!]!
    having: ProjectScalarWhereWithAggregatesInput
    take: Int
    skip: Int
  ): [ProjectGroupBy!]!
  repo(where: RepoWhereUniqueInput!): Repo
  findFirstRepo(
    where: RepoWhereInput
    orderBy: [RepoOrderByWithRelationInput!]
    cursor: RepoWhereUniqueInput
    take: Int
    skip: Int
    distinct: [RepoScalarFieldEnum!]
  ): Repo
  repos(
    where: RepoWhereInput
    orderBy: [RepoOrderByWithRelationInput!]
    cursor: RepoWhereUniqueInput
    take: Int
    skip: Int
    distinct: [RepoScalarFieldEnum!]
  ): [Repo!]!
  aggregateRepo(
    where: RepoWhereInput
    orderBy: [RepoOrderByWithRelationInput!]
    cursor: RepoWhereUniqueInput
    take: Int
    skip: Int
  ): AggregateRepo!
  groupByRepo(
    where: RepoWhereInput
    orderBy: [RepoOrderByWithAggregationInput!]
    by: [RepoScalarFieldEnum!]!
    having: RepoScalarWhereWithAggregatesInput
    take: Int
    skip: Int
  ): [RepoGroupBy!]!
  user(where: UserWhereUniqueInput!): User
  findFirstUser(
    where: UserWhereInput
    orderBy: [UserOrderByWithRelationInput!]
    cursor: UserWhereUniqueInput
    take: Int
    skip: Int
    distinct: [UserScalarFieldEnum!]
  ): User
  users(
    where: UserWhereInput
    orderBy: [UserOrderByWithRelationInput!]
    cursor: UserWhereUniqueInput
    take: Int
    skip: Int
    distinct: [UserScalarFieldEnum!]
  ): [User!]!
  aggregateUser(
    where: UserWhereInput
    orderBy: [UserOrderByWithRelationInput!]
    cursor: UserWhereUniqueInput
    take: Int
    skip: Int
  ): AggregateUser!
  groupByUser(
    where: UserWhereInput
    orderBy: [UserOrderByWithAggregationInput!]
    by: [UserScalarFieldEnum!]!
    having: UserScalarWhereWithAggregatesInput
    take: Int
    skip: Int
  ): [UserGroupBy!]!
  totalClaims: Float!
  lastMonthClaims: Float!
  userClaims(githubId: Float!): [FullClaimData!]
  totalGitPOAPs: Float!
  lastMonthGitPOAPs: Float!
  gitPOAPEvent(id: Float!): FullGitPOAPEventData
  userPOAPs(
    page: Float = null
    perPage: Float = null
    sort: String = "date"
    address: String!
  ): UserPOAPs
  repoGitPOAPs(
    page: Float = null
    perPage: Float = null
    sort: String = "date"
    repoId: Float!
  ): RepoGitPOAPs
  mostClaimedGitPOAPs(count: Float = 10): [GitPOAPWithClaimsCount!]
  profileFeaturedPOAPs(address: String!): UserFeaturedPOAPs
  gitPOAPHolders(
    page: Float = null
    perPage: Float = null
    sort: String = "claim-date"
    gitPOAPId: Float!
  ): Holders
  repoData(
    repoName: String = null
    orgName: String = null
    repoId: Float = null
  ): RepoData
  repoStarCount(repoId: Float!): Float!
  totalRepos: Float!
  lastMonthRepos: Float!
  recentlyAddedRepos(count: Float = 10): [Repo!]!
  allRepos(
    page: Float = null
    perPage: Float = null
    sort: String = "alphabetical"
  ): [Repo!]
  organizationData(
    orgName: String = null
    orgId: Float = null
  ): OrganizationData
  allOrganizations(
    page: Float = null
    perPage: Float = null
    sort: String = "alphabetical"
  ): [Organization!]
  organizationRepos(
    page: Float = null
    perPage: Float = null
    sort: String = "alphabetical"
    orgId: Float!
  ): [RepoData!]
  totalContributors: Float!
  lastMonthContributors: Float!
  profileData(address: String!): NullableProfile
  mostHonoredContributors(count: Float = 10): [ProfileWithClaimsCount!]!
  repoMostHonoredContributors(
    repoId: Float!
    count: Float = 10
  ): [ProfileWithClaimsCount!]!
  search(text: String!): SearchResults!
}

type Claim {
  id: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  mintedAt: DateTime
  status: ClaimStatus!
  poapTokenId: String
  address: String
  gitPOAPId: Int!
  userId: Int!
  pullRequestEarnedId: Int
  gitPOAP: GitPOAP!
  user: User!
  pullRequestEarned: GithubPullRequest
}

# The javascript `Date` as string. Type represents date and time as the ISO Date string.
scalar DateTime

enum ClaimStatus {
  UNCLAIMED
  PENDING
  MINTING
  CLAIMED
}

type GitPOAP {
  id: Int!
  type: ClaimType!
  name: String!
  imageUrl: String!
  description: String!
  year: Int!
  poapEventId: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  projectId: Int!
  status: GitPOAPStatus!
  ongoing: Boolean!
  eventId: Int
  level: Int!
  threshold: Int!
  _count: GitPOAPCount
  project: Project!
  claims(
    where: ClaimWhereInput
    orderBy: [ClaimOrderByWithRelationInput!]
    cursor: ClaimWhereUniqueInput
    take: Int
    skip: Int
    distinct: [ClaimScalarFieldEnum!]
  ): [Claim!]!
  redeemCodes(
    where: RedeemCodeWhereInput
    orderBy: [RedeemCodeOrderByWithRelationInput!]
    cursor: RedeemCodeWhereUniqueInput
    take: Int
    skip: Int
    distinct: [RedeemCodeScalarFieldEnum!]
  ): [RedeemCode!]!
  event: Event
}

enum ClaimType {
  ANNUAL
  QUARTERLY
  MANUAL
}

enum GitPOAPStatus {
  UNAPPROVED
  APPROVED
  REDEEM_REQUEST_PENDING
}

type GitPOAPCount {
  claims: Int!
  redeemCodes: Int!
}

type Project {
  id: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  _count: ProjectCount
  repos(
    where: RepoWhereInput
    orderBy: [RepoOrderByWithRelationInput!]
    cursor: RepoWhereUniqueInput
    take: Int
    skip: Int
    distinct: [RepoScalarFieldEnum!]
  ): [Repo!]!
  gitPOAPs(
    where: GitPOAPWhereInput
    orderBy: [GitPOAPOrderByWithRelationInput!]
    cursor: GitPOAPWhereUniqueInput
    take: Int
    skip: Int
    distinct: [GitPOAPScalarFieldEnum!]
  ): [GitPOAP!]!
}

type ProjectCount {
  repos: Int!
  gitPOAPs: Int!
}

type Repo {
  id: Int!
  name: String!
  githubRepoId: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  organizationId: Int!
  projectId: Int!
  lastPRUpdatedAt: DateTime!
  _count: RepoCount
  organization: Organization!
  GithubPullRequest(
    where: GithubPullRequestWhereInput
    orderBy: [GithubPullRequestOrderByWithRelationInput!]
    cursor: GithubPullRequestWhereUniqueInput
    take: Int
    skip: Int
    distinct: [GithubPullRequestScalarFieldEnum!]
  ): [GithubPullRequest!]!
  project: Project!
}

type RepoCount {
  GithubPullRequest: Int!
}

type Organization {
  id: Int!
  githubOrgId: Int!
  name: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  description: String
  twitterHandle: String
  url: String
  _count: OrganizationCount
  repos(
    where: RepoWhereInput
    orderBy: [RepoOrderByWithRelationInput!]
    cursor: RepoWhereUniqueInput
    take: Int
    skip: Int
    distinct: [RepoScalarFieldEnum!]
  ): [Repo!]!
}

type OrganizationCount {
  repos: Int!
}

input RepoWhereInput {
  AND: [RepoWhereInput!]
  OR: [RepoWhereInput!]
  NOT: [RepoWhereInput!]
  id: IntFilter
  name: StringFilter
  githubRepoId: IntFilter
  createdAt: DateTimeFilter
  updatedAt: DateTimeFilter
  organizationId: IntFilter
  organization: OrganizationRelationFilter
  GithubPullRequest: GithubPullRequestListRelationFilter
  projectId: IntFilter
  project: ProjectRelationFilter
  lastPRUpdatedAt: DateTimeFilter
}

input IntFilter {
  equals: Int
  in: [Int!]
  notIn: [Int!]
  lt: Int
  lte: Int
  gt: Int
  gte: Int
  not: NestedIntFilter
}

input NestedIntFilter {
  equals: Int
  in: [Int!]
  notIn: [Int!]
  lt: Int
  lte: Int
  gt: Int
  gte: Int
  not: NestedIntFilter
}

input StringFilter {
  equals: String
  in: [String!]
  notIn: [String!]
  lt: String
  lte: String
  gt: String
  gte: String
  contains: String
  startsWith: String
  endsWith: String
  mode: QueryMode
  not: NestedStringFilter
}

enum QueryMode {
  default
  insensitive
}

input NestedStringFilter {
  equals: String
  in: [String!]
  notIn: [String!]
  lt: String
  lte: String
  gt: String
  gte: String
  contains: String
  startsWith: String
  endsWith: String
  not: NestedStringFilter
}

input DateTimeFilter {
  equals: DateTime
  in: [DateTime!]
  notIn: [DateTime!]
  lt: DateTime
  lte: DateTime
  gt: DateTime
  gte: DateTime
  not: NestedDateTimeFilter
}

input NestedDateTimeFilter {
  equals: DateTime
  in: [DateTime!]
  notIn: [DateTime!]
  lt: DateTime
  lte: DateTime
  gt: DateTime
  gte: DateTime
  not: NestedDateTimeFilter
}

input OrganizationRelationFilter {
  is: OrganizationWhereInput
  isNot: OrganizationWhereInput
}

input OrganizationWhereInput {
  AND: [OrganizationWhereInput!]
  OR: [OrganizationWhereInput!]
  NOT: [OrganizationWhereInput!]
  id: IntFilter
  githubOrgId: IntFilter
  name: StringFilter
  createdAt: DateTimeFilter
  updatedAt: DateTimeFilter
  description: StringNullableFilter
  twitterHandle: StringNullableFilter
  url: StringNullableFilter
  repos: RepoListRelationFilter
}

input StringNullableFilter {
  equals: String
  in: [String!]
  notIn: [String!]
  lt: String
  lte: String
  gt: String
  gte: String
  contains: String
  startsWith: String
  endsWith: String
  mode: QueryMode
  not: NestedStringNullableFilter
}

input NestedStringNullableFilter {
  equals: String
  in: [String!]
  notIn: [String!]
  lt: String
  lte: String
  gt: String
  gte: String
  contains: String
  startsWith: String
  endsWith: String
  not: NestedStringNullableFilter
}

input RepoListRelationFilter {
  every: RepoWhereInput
  some: RepoWhereInput
  none: RepoWhereInput
}

input GithubPullRequestListRelationFilter {
  every: GithubPullRequestWhereInput
  some: GithubPullRequestWhereInput
  none: GithubPullRequestWhereInput
}

input GithubPullRequestWhereInput {
  AND: [GithubPullRequestWhereInput!]
  OR: [GithubPullRequestWhereInput!]
  NOT: [GithubPullRequestWhereInput!]
  id: IntFilter
  createdAt: DateTimeFilter
  updatedAt: DateTimeFilter
  githubPullNumber: IntFilter
  githubTitle: StringFilter
  githubMergedAt: DateTimeFilter
  githubMergeCommitSha: StringFilter
  repoId: IntFilter
  repo: RepoRelationFilter
  userId: IntFilter
  user: UserRelationFilter
  Claim: ClaimListRelationFilter
}

input RepoRelationFilter {
  is: RepoWhereInput
  isNot: RepoWhereInput
}

input UserRelationFilter {
  is: UserWhereInput
  isNot: UserWhereInput
}

input UserWhereInput {
  AND: [UserWhereInput!]
  OR: [UserWhereInput!]
  NOT: [UserWhereInput!]
  id: IntFilter
  githubId: IntFilter
  githubHandle: StringFilter
  createdAt: DateTimeFilter
  updatedAt: DateTimeFilter
  claims: ClaimListRelationFilter
  GithubPullRequest: GithubPullRequestListRelationFilter
}

input ClaimListRelationFilter {
  every: ClaimWhereInput
  some: ClaimWhereInput
  none: ClaimWhereInput
}

input ClaimWhereInput {
  AND: [ClaimWhereInput!]
  OR: [ClaimWhereInput!]
  NOT: [ClaimWhereInput!]
  id: IntFilter
  createdAt: DateTimeFilter
  updatedAt: DateTimeFilter
  mintedAt: DateTimeNullableFilter
  status: EnumClaimStatusFilter
  poapTokenId: StringNullableFilter
  address: StringNullableFilter
  gitPOAPId: IntFilter
  gitPOAP: GitPOAPRelationFilter
  userId: IntFilter
  user: UserRelationFilter
  pullRequestEarnedId: IntNullableFilter
  pullRequestEarned: GithubPullRequestRelationFilter
}

input DateTimeNullableFilter {
  equals: DateTime
  in: [DateTime!]
  notIn: [DateTime!]
  lt: DateTime
  lte: DateTime
  gt: DateTime
  gte: DateTime
  not: NestedDateTimeNullableFilter
}

input NestedDateTimeNullableFilter {
  equals: DateTime
  in: [DateTime!]
  notIn: [DateTime!]
  lt: DateTime
  lte: DateTime
  gt: DateTime
  gte: DateTime
  not: NestedDateTimeNullableFilter
}

input EnumClaimStatusFilter {
  equals: ClaimStatus
  in: [ClaimStatus!]
  notIn: [ClaimStatus!]
  not: NestedEnumClaimStatusFilter
}

input NestedEnumClaimStatusFilter {
  equals: ClaimStatus
  in: [ClaimStatus!]
  notIn: [ClaimStatus!]
  not: NestedEnumClaimStatusFilter
}

input GitPOAPRelationFilter {
  is: GitPOAPWhereInput
  isNot: GitPOAPWhereInput
}

input GitPOAPWhereInput {
  AND: [GitPOAPWhereInput!]
  OR: [GitPOAPWhereInput!]
  NOT: [GitPOAPWhereInput!]
  id: IntFilter
  type: EnumClaimTypeFilter
  name: StringFilter
  imageUrl: StringFilter
  description: StringFilter
  year: IntFilter
  poapEventId: IntFilter
  createdAt: DateTimeFilter
  updatedAt: DateTimeFilter
  projectId: IntFilter
  project: ProjectRelationFilter
  claims: ClaimListRelationFilter
  status: EnumGitPOAPStatusFilter
  ongoing: BoolFilter
  redeemCodes: RedeemCodeListRelationFilter
  eventId: IntNullableFilter
  event: EventRelationFilter
  level: IntFilter
  threshold: IntFilter
}

input EnumClaimTypeFilter {
  equals: ClaimType
  in: [ClaimType!]
  notIn: [ClaimType!]
  not: NestedEnumClaimTypeFilter
}

input NestedEnumClaimTypeFilter {
  equals: ClaimType
  in: [ClaimType!]
  notIn: [ClaimType!]
  not: NestedEnumClaimTypeFilter
}

input ProjectRelationFilter {
  is: ProjectWhereInput
  isNot: ProjectWhereInput
}

input ProjectWhereInput {
  AND: [ProjectWhereInput!]
  OR: [ProjectWhereInput!]
  NOT: [ProjectWhereInput!]
  id: IntFilter
  createdAt: DateTimeFilter
  updatedAt: DateTimeFilter
  repos: RepoListRelationFilter
  gitPOAPs: GitPOAPListRelationFilter
}

input GitPOAPListRelationFilter {
  every: GitPOAPWhereInput
  some: GitPOAPWhereInput
  none: GitPOAPWhereInput
}

input EnumGitPOAPStatusFilter {
  equals: GitPOAPStatus
  in: [GitPOAPStatus!]
  notIn: [GitPOAPStatus!]
  not: NestedEnumGitPOAPStatusFilter
}

input NestedEnumGitPOAPStatusFilter {
  equals: GitPOAPStatus
  in: [GitPOAPStatus!]
  notIn: [GitPOAPStatus!]
  not: NestedEnumGitPOAPStatusFilter
}

input BoolFilter {
  equals: Boolean
  not: NestedBoolFilter
}

input NestedBoolFilter {
  equals: Boolean
  not: NestedBoolFilter
}

input RedeemCodeListRelationFilter {
  every: RedeemCodeWhereInput
  some: RedeemCodeWhereInput
  none: RedeemCodeWhereInput
}

input RedeemCodeWhereInput {
  AND: [RedeemCodeWhereInput!]
  OR: [RedeemCodeWhereInput!]
  NOT: [RedeemCodeWhereInput!]
  id: IntFilter
  gitPOAPId: IntFilter
  gitPOAP: GitPOAPRelationFilter
  code: StringFilter
}

input IntNullableFilter {
  equals: Int
  in: [Int!]
  notIn: [Int!]
  lt: Int
  lte: Int
  gt: Int
  gte: Int
  not: NestedIntNullableFilter
}

input NestedIntNullableFilter {
  equals: Int
  in: [Int!]
  notIn: [Int!]
  lt: Int
  lte: Int
  gt: Int
  gte: Int
  not: NestedIntNullableFilter
}

input EventRelationFilter {
  is: EventWhereInput
  isNot: EventWhereInput
}

input EventWhereInput {
  AND: [EventWhereInput!]
  OR: [EventWhereInput!]
  NOT: [EventWhereInput!]
  id: IntFilter
  createdAt: DateTimeFilter
  updatedAt: DateTimeFilter
  startDate: DateTimeFilter
  endDate: DateTimeFilter
  name: StringFilter
  organization: StringFilter
  description: StringNullableFilter
  location: StringFilter
  imageUrl: StringNullableFilter
  githubHandle: StringNullableFilter
  twitterHandle: StringNullableFilter
  siteUrl: StringNullableFilter
  GitPOAP: GitPOAPListRelationFilter
}

input GithubPullRequestRelationFilter {
  is: GithubPullRequestWhereInput
  isNot: GithubPullRequestWhereInput
}

input RepoOrderByWithRelationInput {
  id: SortOrder
  name: SortOrder
  githubRepoId: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  organizationId: SortOrder
  organization: OrganizationOrderByWithRelationInput
  GithubPullRequest: GithubPullRequestOrderByRelationAggregateInput
  projectId: SortOrder
  project: ProjectOrderByWithRelationInput
  lastPRUpdatedAt: SortOrder
}

enum SortOrder {
  asc
  desc
}

input OrganizationOrderByWithRelationInput {
  id: SortOrder
  githubOrgId: SortOrder
  name: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  description: SortOrder
  twitterHandle: SortOrder
  url: SortOrder
  repos: RepoOrderByRelationAggregateInput
}

input RepoOrderByRelationAggregateInput {
  _count: SortOrder
}

input GithubPullRequestOrderByRelationAggregateInput {
  _count: SortOrder
}

input ProjectOrderByWithRelationInput {
  id: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  repos: RepoOrderByRelationAggregateInput
  gitPOAPs: GitPOAPOrderByRelationAggregateInput
}

input GitPOAPOrderByRelationAggregateInput {
  _count: SortOrder
}

input RepoWhereUniqueInput {
  id: Int
  githubRepoId: Int
}

enum RepoScalarFieldEnum {
  id
  name
  githubRepoId
  createdAt
  updatedAt
  organizationId
  projectId
  lastPRUpdatedAt
}

type GithubPullRequest {
  id: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  githubPullNumber: Int!
  githubTitle: String!
  githubMergedAt: DateTime!
  githubMergeCommitSha: String!
  repoId: Int!
  userId: Int!
  _count: GithubPullRequestCount
  repo: Repo!
  user: User!
  Claim(
    where: ClaimWhereInput
    orderBy: [ClaimOrderByWithRelationInput!]
    cursor: ClaimWhereUniqueInput
    take: Int
    skip: Int
    distinct: [ClaimScalarFieldEnum!]
  ): [Claim!]!
}

type GithubPullRequestCount {
  Claim: Int!
}

type User {
  id: Int!
  githubId: Int!
  githubHandle: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  _count: UserCount
  claims(
    where: ClaimWhereInput
    orderBy: [ClaimOrderByWithRelationInput!]
    cursor: ClaimWhereUniqueInput
    take: Int
    skip: Int
    distinct: [ClaimScalarFieldEnum!]
  ): [Claim!]!
  GithubPullRequest(
    where: GithubPullRequestWhereInput
    orderBy: [GithubPullRequestOrderByWithRelationInput!]
    cursor: GithubPullRequestWhereUniqueInput
    take: Int
    skip: Int
    distinct: [GithubPullRequestScalarFieldEnum!]
  ): [GithubPullRequest!]!
}

type UserCount {
  claims: Int!
  authTokens: Int!
  GithubPullRequest: Int!
}

input ClaimOrderByWithRelationInput {
  id: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  mintedAt: SortOrder
  status: SortOrder
  poapTokenId: SortOrder
  address: SortOrder
  gitPOAPId: SortOrder
  gitPOAP: GitPOAPOrderByWithRelationInput
  userId: SortOrder
  user: UserOrderByWithRelationInput
  pullRequestEarnedId: SortOrder
  pullRequestEarned: GithubPullRequestOrderByWithRelationInput
}

input GitPOAPOrderByWithRelationInput {
  id: SortOrder
  type: SortOrder
  name: SortOrder
  imageUrl: SortOrder
  description: SortOrder
  year: SortOrder
  poapEventId: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  projectId: SortOrder
  project: ProjectOrderByWithRelationInput
  claims: ClaimOrderByRelationAggregateInput
  status: SortOrder
  ongoing: SortOrder
  redeemCodes: RedeemCodeOrderByRelationAggregateInput
  eventId: SortOrder
  event: EventOrderByWithRelationInput
  level: SortOrder
  threshold: SortOrder
}

input ClaimOrderByRelationAggregateInput {
  _count: SortOrder
}

input RedeemCodeOrderByRelationAggregateInput {
  _count: SortOrder
}

input EventOrderByWithRelationInput {
  id: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  startDate: SortOrder
  endDate: SortOrder
  name: SortOrder
  organization: SortOrder
  description: SortOrder
  location: SortOrder
  imageUrl: SortOrder
  githubHandle: SortOrder
  twitterHandle: SortOrder
  siteUrl: SortOrder
  GitPOAP: GitPOAPOrderByRelationAggregateInput
}

input UserOrderByWithRelationInput {
  id: SortOrder
  githubId: SortOrder
  githubHandle: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  claims: ClaimOrderByRelationAggregateInput
  GithubPullRequest: GithubPullRequestOrderByRelationAggregateInput
}

input GithubPullRequestOrderByWithRelationInput {
  id: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  githubPullNumber: SortOrder
  githubTitle: SortOrder
  githubMergedAt: SortOrder
  githubMergeCommitSha: SortOrder
  repoId: SortOrder
  repo: RepoOrderByWithRelationInput
  userId: SortOrder
  user: UserOrderByWithRelationInput
  Claim: ClaimOrderByRelationAggregateInput
}

input ClaimWhereUniqueInput {
  id: Int
  poapTokenId: String
  gitPOAPId_userId: ClaimGitPOAPIdUserIdCompoundUniqueInput
}

input ClaimGitPOAPIdUserIdCompoundUniqueInput {
  gitPOAPId: Int!
  userId: Int!
}

enum ClaimScalarFieldEnum {
  id
  createdAt
  updatedAt
  mintedAt
  status
  qrHash
  poapTokenId
  address
  gitPOAPId
  userId
  pullRequestEarnedId
}

input GithubPullRequestWhereUniqueInput {
  id: Int
  repoId_githubPullNumber: GithubPullRequestRepoIdGithubPullNumberCompoundUniqueInput
}

input GithubPullRequestRepoIdGithubPullNumberCompoundUniqueInput {
  repoId: Int!
  githubPullNumber: Int!
}

enum GithubPullRequestScalarFieldEnum {
  id
  createdAt
  updatedAt
  githubPullNumber
  githubTitle
  githubMergedAt
  githubMergeCommitSha
  repoId
  userId
}

input GitPOAPWhereUniqueInput {
  id: Int
  poapEventId: Int
}

enum GitPOAPScalarFieldEnum {
  id
  type
  name
  imageUrl
  description
  year
  poapEventId
  createdAt
  updatedAt
  projectId
  poapSecret
  status
  ongoing
  eventId
  level
  threshold
}

type RedeemCode {
  id: Int!
  gitPOAPId: Int!
  code: String!
}

input RedeemCodeOrderByWithRelationInput {
  id: SortOrder
  gitPOAPId: SortOrder
  gitPOAP: GitPOAPOrderByWithRelationInput
  code: SortOrder
}

input RedeemCodeWhereUniqueInput {
  id: Int
  gitPOAPId_code: RedeemCodeGitPOAPIdCodeCompoundUniqueInput
}

input RedeemCodeGitPOAPIdCodeCompoundUniqueInput {
  gitPOAPId: Int!
  code: String!
}

enum RedeemCodeScalarFieldEnum {
  id
  gitPOAPId
  code
}

type Event {
  id: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  startDate: DateTime!
  endDate: DateTime!
  name: String!
  organization: String!
  description: String
  location: String!
  imageUrl: String
  githubHandle: String
  twitterHandle: String
  siteUrl: String
  _count: EventCount
}

type EventCount {
  GitPOAP: Int!
}

type AggregateClaim {
  _count: ClaimCountAggregate
  _avg: ClaimAvgAggregate
  _sum: ClaimSumAggregate
  _min: ClaimMinAggregate
  _max: ClaimMaxAggregate
}

type ClaimCountAggregate {
  id: Int!
  createdAt: Int!
  updatedAt: Int!
  mintedAt: Int!
  status: Int!
  qrHash: Int!
  poapTokenId: Int!
  address: Int!
  gitPOAPId: Int!
  userId: Int!
  pullRequestEarnedId: Int!
  _all: Int!
}

type ClaimAvgAggregate {
  id: Float
  gitPOAPId: Float
  userId: Float
  pullRequestEarnedId: Float
}

type ClaimSumAggregate {
  id: Int
  gitPOAPId: Int
  userId: Int
  pullRequestEarnedId: Int
}

type ClaimMinAggregate {
  id: Int
  createdAt: DateTime
  updatedAt: DateTime
  mintedAt: DateTime
  status: ClaimStatus
  qrHash: String
  poapTokenId: String
  address: String
  gitPOAPId: Int
  userId: Int
  pullRequestEarnedId: Int
}

type ClaimMaxAggregate {
  id: Int
  createdAt: DateTime
  updatedAt: DateTime
  mintedAt: DateTime
  status: ClaimStatus
  qrHash: String
  poapTokenId: String
  address: String
  gitPOAPId: Int
  userId: Int
  pullRequestEarnedId: Int
}

type ClaimGroupBy {
  id: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  mintedAt: DateTime
  status: ClaimStatus!
  qrHash: String
  poapTokenId: String
  address: String
  gitPOAPId: Int!
  userId: Int!
  pullRequestEarnedId: Int
  _count: ClaimCountAggregate
  _avg: ClaimAvgAggregate
  _sum: ClaimSumAggregate
  _min: ClaimMinAggregate
  _max: ClaimMaxAggregate
}

input ClaimOrderByWithAggregationInput {
  id: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  mintedAt: SortOrder
  status: SortOrder
  poapTokenId: SortOrder
  address: SortOrder
  gitPOAPId: SortOrder
  userId: SortOrder
  pullRequestEarnedId: SortOrder
  _count: ClaimCountOrderByAggregateInput
  _avg: ClaimAvgOrderByAggregateInput
  _max: ClaimMaxOrderByAggregateInput
  _min: ClaimMinOrderByAggregateInput
  _sum: ClaimSumOrderByAggregateInput
}

input ClaimCountOrderByAggregateInput {
  id: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  mintedAt: SortOrder
  status: SortOrder
  poapTokenId: SortOrder
  address: SortOrder
  gitPOAPId: SortOrder
  userId: SortOrder
  pullRequestEarnedId: SortOrder
}

input ClaimAvgOrderByAggregateInput {
  id: SortOrder
  gitPOAPId: SortOrder
  userId: SortOrder
  pullRequestEarnedId: SortOrder
}

input ClaimMaxOrderByAggregateInput {
  id: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  mintedAt: SortOrder
  status: SortOrder
  poapTokenId: SortOrder
  address: SortOrder
  gitPOAPId: SortOrder
  userId: SortOrder
  pullRequestEarnedId: SortOrder
}

input ClaimMinOrderByAggregateInput {
  id: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  mintedAt: SortOrder
  status: SortOrder
  poapTokenId: SortOrder
  address: SortOrder
  gitPOAPId: SortOrder
  userId: SortOrder
  pullRequestEarnedId: SortOrder
}

input ClaimSumOrderByAggregateInput {
  id: SortOrder
  gitPOAPId: SortOrder
  userId: SortOrder
  pullRequestEarnedId: SortOrder
}

input ClaimScalarWhereWithAggregatesInput {
  AND: [ClaimScalarWhereWithAggregatesInput!]
  OR: [ClaimScalarWhereWithAggregatesInput!]
  NOT: [ClaimScalarWhereWithAggregatesInput!]
  id: IntWithAggregatesFilter
  createdAt: DateTimeWithAggregatesFilter
  updatedAt: DateTimeWithAggregatesFilter
  mintedAt: DateTimeNullableWithAggregatesFilter
  status: EnumClaimStatusWithAggregatesFilter
  poapTokenId: StringNullableWithAggregatesFilter
  address: StringNullableWithAggregatesFilter
  gitPOAPId: IntWithAggregatesFilter
  userId: IntWithAggregatesFilter
  pullRequestEarnedId: IntNullableWithAggregatesFilter
}

input IntWithAggregatesFilter {
  equals: Int
  in: [Int!]
  notIn: [Int!]
  lt: Int
  lte: Int
  gt: Int
  gte: Int
  not: NestedIntWithAggregatesFilter
  _count: NestedIntFilter
  _avg: NestedFloatFilter
  _sum: NestedIntFilter
  _min: NestedIntFilter
  _max: NestedIntFilter
}

input NestedIntWithAggregatesFilter {
  equals: Int
  in: [Int!]
  notIn: [Int!]
  lt: Int
  lte: Int
  gt: Int
  gte: Int
  not: NestedIntWithAggregatesFilter
  _count: NestedIntFilter
  _avg: NestedFloatFilter
  _sum: NestedIntFilter
  _min: NestedIntFilter
  _max: NestedIntFilter
}

input NestedFloatFilter {
  equals: Float
  in: [Float!]
  notIn: [Float!]
  lt: Float
  lte: Float
  gt: Float
  gte: Float
  not: NestedFloatFilter
}

input DateTimeWithAggregatesFilter {
  equals: DateTime
  in: [DateTime!]
  notIn: [DateTime!]
  lt: DateTime
  lte: DateTime
  gt: DateTime
  gte: DateTime
  not: NestedDateTimeWithAggregatesFilter
  _count: NestedIntFilter
  _min: NestedDateTimeFilter
  _max: NestedDateTimeFilter
}

input NestedDateTimeWithAggregatesFilter {
  equals: DateTime
  in: [DateTime!]
  notIn: [DateTime!]
  lt: DateTime
  lte: DateTime
  gt: DateTime
  gte: DateTime
  not: NestedDateTimeWithAggregatesFilter
  _count: NestedIntFilter
  _min: NestedDateTimeFilter
  _max: NestedDateTimeFilter
}

input DateTimeNullableWithAggregatesFilter {
  equals: DateTime
  in: [DateTime!]
  notIn: [DateTime!]
  lt: DateTime
  lte: DateTime
  gt: DateTime
  gte: DateTime
  not: NestedDateTimeNullableWithAggregatesFilter
  _count: NestedIntNullableFilter
  _min: NestedDateTimeNullableFilter
  _max: NestedDateTimeNullableFilter
}

input NestedDateTimeNullableWithAggregatesFilter {
  equals: DateTime
  in: [DateTime!]
  notIn: [DateTime!]
  lt: DateTime
  lte: DateTime
  gt: DateTime
  gte: DateTime
  not: NestedDateTimeNullableWithAggregatesFilter
  _count: NestedIntNullableFilter
  _min: NestedDateTimeNullableFilter
  _max: NestedDateTimeNullableFilter
}

input EnumClaimStatusWithAggregatesFilter {
  equals: ClaimStatus
  in: [ClaimStatus!]
  notIn: [ClaimStatus!]
  not: NestedEnumClaimStatusWithAggregatesFilter
  _count: NestedIntFilter
  _min: NestedEnumClaimStatusFilter
  _max: NestedEnumClaimStatusFilter
}

input NestedEnumClaimStatusWithAggregatesFilter {
  equals: ClaimStatus
  in: [ClaimStatus!]
  notIn: [ClaimStatus!]
  not: NestedEnumClaimStatusWithAggregatesFilter
  _count: NestedIntFilter
  _min: NestedEnumClaimStatusFilter
  _max: NestedEnumClaimStatusFilter
}

input StringNullableWithAggregatesFilter {
  equals: String
  in: [String!]
  notIn: [String!]
  lt: String
  lte: String
  gt: String
  gte: String
  contains: String
  startsWith: String
  endsWith: String
  mode: QueryMode
  not: NestedStringNullableWithAggregatesFilter
  _count: NestedIntNullableFilter
  _min: NestedStringNullableFilter
  _max: NestedStringNullableFilter
}

input NestedStringNullableWithAggregatesFilter {
  equals: String
  in: [String!]
  notIn: [String!]
  lt: String
  lte: String
  gt: String
  gte: String
  contains: String
  startsWith: String
  endsWith: String
  not: NestedStringNullableWithAggregatesFilter
  _count: NestedIntNullableFilter
  _min: NestedStringNullableFilter
  _max: NestedStringNullableFilter
}

input IntNullableWithAggregatesFilter {
  equals: Int
  in: [Int!]
  notIn: [Int!]
  lt: Int
  lte: Int
  gt: Int
  gte: Int
  not: NestedIntNullableWithAggregatesFilter
  _count: NestedIntNullableFilter
  _avg: NestedFloatNullableFilter
  _sum: NestedIntNullableFilter
  _min: NestedIntNullableFilter
  _max: NestedIntNullableFilter
}

input NestedIntNullableWithAggregatesFilter {
  equals: Int
  in: [Int!]
  notIn: [Int!]
  lt: Int
  lte: Int
  gt: Int
  gte: Int
  not: NestedIntNullableWithAggregatesFilter
  _count: NestedIntNullableFilter
  _avg: NestedFloatNullableFilter
  _sum: NestedIntNullableFilter
  _min: NestedIntNullableFilter
  _max: NestedIntNullableFilter
}

input NestedFloatNullableFilter {
  equals: Float
  in: [Float!]
  notIn: [Float!]
  lt: Float
  lte: Float
  gt: Float
  gte: Float
  not: NestedFloatNullableFilter
}

type FeaturedPOAP {
  id: Int!
  poapTokenId: String!
  profileId: Int!
  profile: Profile!
}

type Profile {
  id: Int!
  address: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  bio: String
  bannerImageUrl: String
  name: String
  profileImageUrl: String
  githubHandle: String
  twitterHandle: String
  personalSiteUrl: String
  isVisibleOnLeaderboard: Boolean!
  _count: ProfileCount
  featuredPOAPs(
    where: FeaturedPOAPWhereInput
    orderBy: [FeaturedPOAPOrderByWithRelationInput!]
    cursor: FeaturedPOAPWhereUniqueInput
    take: Int
    skip: Int
    distinct: [FeaturedPOAPScalarFieldEnum!]
  ): [FeaturedPOAP!]!
}

type ProfileCount {
  featuredPOAPs: Int!
}

input FeaturedPOAPWhereInput {
  AND: [FeaturedPOAPWhereInput!]
  OR: [FeaturedPOAPWhereInput!]
  NOT: [FeaturedPOAPWhereInput!]
  id: IntFilter
  poapTokenId: StringFilter
  profileId: IntFilter
  profile: ProfileRelationFilter
}

input ProfileRelationFilter {
  is: ProfileWhereInput
  isNot: ProfileWhereInput
}

input ProfileWhereInput {
  AND: [ProfileWhereInput!]
  OR: [ProfileWhereInput!]
  NOT: [ProfileWhereInput!]
  id: IntFilter
  address: StringFilter
  createdAt: DateTimeFilter
  updatedAt: DateTimeFilter
  bio: StringNullableFilter
  bannerImageUrl: StringNullableFilter
  name: StringNullableFilter
  profileImageUrl: StringNullableFilter
  githubHandle: StringNullableFilter
  twitterHandle: StringNullableFilter
  personalSiteUrl: StringNullableFilter
  isVisibleOnLeaderboard: BoolFilter
  featuredPOAPs: FeaturedPOAPListRelationFilter
}

input FeaturedPOAPListRelationFilter {
  every: FeaturedPOAPWhereInput
  some: FeaturedPOAPWhereInput
  none: FeaturedPOAPWhereInput
}

input FeaturedPOAPOrderByWithRelationInput {
  id: SortOrder
  poapTokenId: SortOrder
  profileId: SortOrder
  profile: ProfileOrderByWithRelationInput
}

input ProfileOrderByWithRelationInput {
  id: SortOrder
  address: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  bio: SortOrder
  bannerImageUrl: SortOrder
  name: SortOrder
  profileImageUrl: SortOrder
  githubHandle: SortOrder
  twitterHandle: SortOrder
  personalSiteUrl: SortOrder
  isVisibleOnLeaderboard: SortOrder
  featuredPOAPs: FeaturedPOAPOrderByRelationAggregateInput
}

input FeaturedPOAPOrderByRelationAggregateInput {
  _count: SortOrder
}

input FeaturedPOAPWhereUniqueInput {
  id: Int
  poapTokenId: String
  poapTokenId_profileId: FeaturedPOAPPoapTokenIdProfileIdCompoundUniqueInput
}

input FeaturedPOAPPoapTokenIdProfileIdCompoundUniqueInput {
  poapTokenId: String!
  profileId: Int!
}

enum FeaturedPOAPScalarFieldEnum {
  id
  poapTokenId
  profileId
}

type AggregateFeaturedPOAP {
  _count: FeaturedPOAPCountAggregate
  _avg: FeaturedPOAPAvgAggregate
  _sum: FeaturedPOAPSumAggregate
  _min: FeaturedPOAPMinAggregate
  _max: FeaturedPOAPMaxAggregate
}

type FeaturedPOAPCountAggregate {
  id: Int!
  poapTokenId: Int!
  profileId: Int!
  _all: Int!
}

type FeaturedPOAPAvgAggregate {
  id: Float
  profileId: Float
}

type FeaturedPOAPSumAggregate {
  id: Int
  profileId: Int
}

type FeaturedPOAPMinAggregate {
  id: Int
  poapTokenId: String
  profileId: Int
}

type FeaturedPOAPMaxAggregate {
  id: Int
  poapTokenId: String
  profileId: Int
}

type FeaturedPOAPGroupBy {
  id: Int!
  poapTokenId: String!
  profileId: Int!
  _count: FeaturedPOAPCountAggregate
  _avg: FeaturedPOAPAvgAggregate
  _sum: FeaturedPOAPSumAggregate
  _min: FeaturedPOAPMinAggregate
  _max: FeaturedPOAPMaxAggregate
}

input FeaturedPOAPOrderByWithAggregationInput {
  id: SortOrder
  poapTokenId: SortOrder
  profileId: SortOrder
  _count: FeaturedPOAPCountOrderByAggregateInput
  _avg: FeaturedPOAPAvgOrderByAggregateInput
  _max: FeaturedPOAPMaxOrderByAggregateInput
  _min: FeaturedPOAPMinOrderByAggregateInput
  _sum: FeaturedPOAPSumOrderByAggregateInput
}

input FeaturedPOAPCountOrderByAggregateInput {
  id: SortOrder
  poapTokenId: SortOrder
  profileId: SortOrder
}

input FeaturedPOAPAvgOrderByAggregateInput {
  id: SortOrder
  profileId: SortOrder
}

input FeaturedPOAPMaxOrderByAggregateInput {
  id: SortOrder
  poapTokenId: SortOrder
  profileId: SortOrder
}

input FeaturedPOAPMinOrderByAggregateInput {
  id: SortOrder
  poapTokenId: SortOrder
  profileId: SortOrder
}

input FeaturedPOAPSumOrderByAggregateInput {
  id: SortOrder
  profileId: SortOrder
}

input FeaturedPOAPScalarWhereWithAggregatesInput {
  AND: [FeaturedPOAPScalarWhereWithAggregatesInput!]
  OR: [FeaturedPOAPScalarWhereWithAggregatesInput!]
  NOT: [FeaturedPOAPScalarWhereWithAggregatesInput!]
  id: IntWithAggregatesFilter
  poapTokenId: StringWithAggregatesFilter
  profileId: IntWithAggregatesFilter
}

input StringWithAggregatesFilter {
  equals: String
  in: [String!]
  notIn: [String!]
  lt: String
  lte: String
  gt: String
  gte: String
  contains: String
  startsWith: String
  endsWith: String
  mode: QueryMode
  not: NestedStringWithAggregatesFilter
  _count: NestedIntFilter
  _min: NestedStringFilter
  _max: NestedStringFilter
}

input NestedStringWithAggregatesFilter {
  equals: String
  in: [String!]
  notIn: [String!]
  lt: String
  lte: String
  gt: String
  gte: String
  contains: String
  startsWith: String
  endsWith: String
  not: NestedStringWithAggregatesFilter
  _count: NestedIntFilter
  _min: NestedStringFilter
  _max: NestedStringFilter
}

type AggregateGitPOAP {
  _count: GitPOAPCountAggregate
  _avg: GitPOAPAvgAggregate
  _sum: GitPOAPSumAggregate
  _min: GitPOAPMinAggregate
  _max: GitPOAPMaxAggregate
}

type GitPOAPCountAggregate {
  id: Int!
  type: Int!
  name: Int!
  imageUrl: Int!
  description: Int!
  year: Int!
  poapEventId: Int!
  createdAt: Int!
  updatedAt: Int!
  projectId: Int!
  poapSecret: Int!
  status: Int!
  ongoing: Int!
  eventId: Int!
  level: Int!
  threshold: Int!
  _all: Int!
}

type GitPOAPAvgAggregate {
  id: Float
  year: Float
  poapEventId: Float
  projectId: Float
  eventId: Float
  level: Float
  threshold: Float
}

type GitPOAPSumAggregate {
  id: Int
  year: Int
  poapEventId: Int
  projectId: Int
  eventId: Int
  level: Int
  threshold: Int
}

type GitPOAPMinAggregate {
  id: Int
  type: ClaimType
  name: String
  imageUrl: String
  description: String
  year: Int
  poapEventId: Int
  createdAt: DateTime
  updatedAt: DateTime
  projectId: Int
  poapSecret: String
  status: GitPOAPStatus
  ongoing: Boolean
  eventId: Int
  level: Int
  threshold: Int
}

type GitPOAPMaxAggregate {
  id: Int
  type: ClaimType
  name: String
  imageUrl: String
  description: String
  year: Int
  poapEventId: Int
  createdAt: DateTime
  updatedAt: DateTime
  projectId: Int
  poapSecret: String
  status: GitPOAPStatus
  ongoing: Boolean
  eventId: Int
  level: Int
  threshold: Int
}

type GitPOAPGroupBy {
  id: Int!
  type: ClaimType!
  name: String!
  imageUrl: String!
  description: String!
  year: Int!
  poapEventId: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  projectId: Int!
  poapSecret: String!
  status: GitPOAPStatus!
  ongoing: Boolean!
  eventId: Int
  level: Int!
  threshold: Int!
  _count: GitPOAPCountAggregate
  _avg: GitPOAPAvgAggregate
  _sum: GitPOAPSumAggregate
  _min: GitPOAPMinAggregate
  _max: GitPOAPMaxAggregate
}

input GitPOAPOrderByWithAggregationInput {
  id: SortOrder
  type: SortOrder
  name: SortOrder
  imageUrl: SortOrder
  description: SortOrder
  year: SortOrder
  poapEventId: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  projectId: SortOrder
  status: SortOrder
  ongoing: SortOrder
  eventId: SortOrder
  level: SortOrder
  threshold: SortOrder
  _count: GitPOAPCountOrderByAggregateInput
  _avg: GitPOAPAvgOrderByAggregateInput
  _max: GitPOAPMaxOrderByAggregateInput
  _min: GitPOAPMinOrderByAggregateInput
  _sum: GitPOAPSumOrderByAggregateInput
}

input GitPOAPCountOrderByAggregateInput {
  id: SortOrder
  type: SortOrder
  name: SortOrder
  imageUrl: SortOrder
  description: SortOrder
  year: SortOrder
  poapEventId: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  projectId: SortOrder
  status: SortOrder
  ongoing: SortOrder
  eventId: SortOrder
  level: SortOrder
  threshold: SortOrder
}

input GitPOAPAvgOrderByAggregateInput {
  id: SortOrder
  year: SortOrder
  poapEventId: SortOrder
  projectId: SortOrder
  eventId: SortOrder
  level: SortOrder
  threshold: SortOrder
}

input GitPOAPMaxOrderByAggregateInput {
  id: SortOrder
  type: SortOrder
  name: SortOrder
  imageUrl: SortOrder
  description: SortOrder
  year: SortOrder
  poapEventId: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  projectId: SortOrder
  status: SortOrder
  ongoing: SortOrder
  eventId: SortOrder
  level: SortOrder
  threshold: SortOrder
}

input GitPOAPMinOrderByAggregateInput {
  id: SortOrder
  type: SortOrder
  name: SortOrder
  imageUrl: SortOrder
  description: SortOrder
  year: SortOrder
  poapEventId: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  projectId: SortOrder
  status: SortOrder
  ongoing: SortOrder
  eventId: SortOrder
  level: SortOrder
  threshold: SortOrder
}

input GitPOAPSumOrderByAggregateInput {
  id: SortOrder
  year: SortOrder
  poapEventId: SortOrder
  projectId: SortOrder
  eventId: SortOrder
  level: SortOrder
  threshold: SortOrder
}

input GitPOAPScalarWhereWithAggregatesInput {
  AND: [GitPOAPScalarWhereWithAggregatesInput!]
  OR: [GitPOAPScalarWhereWithAggregatesInput!]
  NOT: [GitPOAPScalarWhereWithAggregatesInput!]
  id: IntWithAggregatesFilter
  type: EnumClaimTypeWithAggregatesFilter
  name: StringWithAggregatesFilter
  imageUrl: StringWithAggregatesFilter
  description: StringWithAggregatesFilter
  year: IntWithAggregatesFilter
  poapEventId: IntWithAggregatesFilter
  createdAt: DateTimeWithAggregatesFilter
  updatedAt: DateTimeWithAggregatesFilter
  projectId: IntWithAggregatesFilter
  status: EnumGitPOAPStatusWithAggregatesFilter
  ongoing: BoolWithAggregatesFilter
  eventId: IntNullableWithAggregatesFilter
  level: IntWithAggregatesFilter
  threshold: IntWithAggregatesFilter
}

input EnumClaimTypeWithAggregatesFilter {
  equals: ClaimType
  in: [ClaimType!]
  notIn: [ClaimType!]
  not: NestedEnumClaimTypeWithAggregatesFilter
  _count: NestedIntFilter
  _min: NestedEnumClaimTypeFilter
  _max: NestedEnumClaimTypeFilter
}

input NestedEnumClaimTypeWithAggregatesFilter {
  equals: ClaimType
  in: [ClaimType!]
  notIn: [ClaimType!]
  not: NestedEnumClaimTypeWithAggregatesFilter
  _count: NestedIntFilter
  _min: NestedEnumClaimTypeFilter
  _max: NestedEnumClaimTypeFilter
}

input EnumGitPOAPStatusWithAggregatesFilter {
  equals: GitPOAPStatus
  in: [GitPOAPStatus!]
  notIn: [GitPOAPStatus!]
  not: NestedEnumGitPOAPStatusWithAggregatesFilter
  _count: NestedIntFilter
  _min: NestedEnumGitPOAPStatusFilter
  _max: NestedEnumGitPOAPStatusFilter
}

input NestedEnumGitPOAPStatusWithAggregatesFilter {
  equals: GitPOAPStatus
  in: [GitPOAPStatus!]
  notIn: [GitPOAPStatus!]
  not: NestedEnumGitPOAPStatusWithAggregatesFilter
  _count: NestedIntFilter
  _min: NestedEnumGitPOAPStatusFilter
  _max: NestedEnumGitPOAPStatusFilter
}

input BoolWithAggregatesFilter {
  equals: Boolean
  not: NestedBoolWithAggregatesFilter
  _count: NestedIntFilter
  _min: NestedBoolFilter
  _max: NestedBoolFilter
}

input NestedBoolWithAggregatesFilter {
  equals: Boolean
  not: NestedBoolWithAggregatesFilter
  _count: NestedIntFilter
  _min: NestedBoolFilter
  _max: NestedBoolFilter
}

type AggregateGithubPullRequest {
  _count: GithubPullRequestCountAggregate
  _avg: GithubPullRequestAvgAggregate
  _sum: GithubPullRequestSumAggregate
  _min: GithubPullRequestMinAggregate
  _max: GithubPullRequestMaxAggregate
}

type GithubPullRequestCountAggregate {
  id: Int!
  createdAt: Int!
  updatedAt: Int!
  githubPullNumber: Int!
  githubTitle: Int!
  githubMergedAt: Int!
  githubMergeCommitSha: Int!
  repoId: Int!
  userId: Int!
  _all: Int!
}

type GithubPullRequestAvgAggregate {
  id: Float
  githubPullNumber: Float
  repoId: Float
  userId: Float
}

type GithubPullRequestSumAggregate {
  id: Int
  githubPullNumber: Int
  repoId: Int
  userId: Int
}

type GithubPullRequestMinAggregate {
  id: Int
  createdAt: DateTime
  updatedAt: DateTime
  githubPullNumber: Int
  githubTitle: String
  githubMergedAt: DateTime
  githubMergeCommitSha: String
  repoId: Int
  userId: Int
}

type GithubPullRequestMaxAggregate {
  id: Int
  createdAt: DateTime
  updatedAt: DateTime
  githubPullNumber: Int
  githubTitle: String
  githubMergedAt: DateTime
  githubMergeCommitSha: String
  repoId: Int
  userId: Int
}

type GithubPullRequestGroupBy {
  id: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  githubPullNumber: Int!
  githubTitle: String!
  githubMergedAt: DateTime!
  githubMergeCommitSha: String!
  repoId: Int!
  userId: Int!
  _count: GithubPullRequestCountAggregate
  _avg: GithubPullRequestAvgAggregate
  _sum: GithubPullRequestSumAggregate
  _min: GithubPullRequestMinAggregate
  _max: GithubPullRequestMaxAggregate
}

input GithubPullRequestOrderByWithAggregationInput {
  id: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  githubPullNumber: SortOrder
  githubTitle: SortOrder
  githubMergedAt: SortOrder
  githubMergeCommitSha: SortOrder
  repoId: SortOrder
  userId: SortOrder
  _count: GithubPullRequestCountOrderByAggregateInput
  _avg: GithubPullRequestAvgOrderByAggregateInput
  _max: GithubPullRequestMaxOrderByAggregateInput
  _min: GithubPullRequestMinOrderByAggregateInput
  _sum: GithubPullRequestSumOrderByAggregateInput
}

input GithubPullRequestCountOrderByAggregateInput {
  id: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  githubPullNumber: SortOrder
  githubTitle: SortOrder
  githubMergedAt: SortOrder
  githubMergeCommitSha: SortOrder
  repoId: SortOrder
  userId: SortOrder
}

input GithubPullRequestAvgOrderByAggregateInput {
  id: SortOrder
  githubPullNumber: SortOrder
  repoId: SortOrder
  userId: SortOrder
}

input GithubPullRequestMaxOrderByAggregateInput {
  id: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  githubPullNumber: SortOrder
  githubTitle: SortOrder
  githubMergedAt: SortOrder
  githubMergeCommitSha: SortOrder
  repoId: SortOrder
  userId: SortOrder
}

input GithubPullRequestMinOrderByAggregateInput {
  id: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  githubPullNumber: SortOrder
  githubTitle: SortOrder
  githubMergedAt: SortOrder
  githubMergeCommitSha: SortOrder
  repoId: SortOrder
  userId: SortOrder
}

input GithubPullRequestSumOrderByAggregateInput {
  id: SortOrder
  githubPullNumber: SortOrder
  repoId: SortOrder
  userId: SortOrder
}

input GithubPullRequestScalarWhereWithAggregatesInput {
  AND: [GithubPullRequestScalarWhereWithAggregatesInput!]
  OR: [GithubPullRequestScalarWhereWithAggregatesInput!]
  NOT: [GithubPullRequestScalarWhereWithAggregatesInput!]
  id: IntWithAggregatesFilter
  createdAt: DateTimeWithAggregatesFilter
  updatedAt: DateTimeWithAggregatesFilter
  githubPullNumber: IntWithAggregatesFilter
  githubTitle: StringWithAggregatesFilter
  githubMergedAt: DateTimeWithAggregatesFilter
  githubMergeCommitSha: StringWithAggregatesFilter
  repoId: IntWithAggregatesFilter
  userId: IntWithAggregatesFilter
}

input OrganizationWhereUniqueInput {
  id: Int
  githubOrgId: Int
}

enum OrganizationScalarFieldEnum {
  id
  githubOrgId
  name
  createdAt
  updatedAt
  description
  twitterHandle
  url
}

type AggregateOrganization {
  _count: OrganizationCountAggregate
  _avg: OrganizationAvgAggregate
  _sum: OrganizationSumAggregate
  _min: OrganizationMinAggregate
  _max: OrganizationMaxAggregate
}

type OrganizationCountAggregate {
  id: Int!
  githubOrgId: Int!
  name: Int!
  createdAt: Int!
  updatedAt: Int!
  description: Int!
  twitterHandle: Int!
  url: Int!
  _all: Int!
}

type OrganizationAvgAggregate {
  id: Float
  githubOrgId: Float
}

type OrganizationSumAggregate {
  id: Int
  githubOrgId: Int
}

type OrganizationMinAggregate {
  id: Int
  githubOrgId: Int
  name: String
  createdAt: DateTime
  updatedAt: DateTime
  description: String
  twitterHandle: String
  url: String
}

type OrganizationMaxAggregate {
  id: Int
  githubOrgId: Int
  name: String
  createdAt: DateTime
  updatedAt: DateTime
  description: String
  twitterHandle: String
  url: String
}

type OrganizationGroupBy {
  id: Int!
  githubOrgId: Int!
  name: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  description: String
  twitterHandle: String
  url: String
  _count: OrganizationCountAggregate
  _avg: OrganizationAvgAggregate
  _sum: OrganizationSumAggregate
  _min: OrganizationMinAggregate
  _max: OrganizationMaxAggregate
}

input OrganizationOrderByWithAggregationInput {
  id: SortOrder
  githubOrgId: SortOrder
  name: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  description: SortOrder
  twitterHandle: SortOrder
  url: SortOrder
  _count: OrganizationCountOrderByAggregateInput
  _avg: OrganizationAvgOrderByAggregateInput
  _max: OrganizationMaxOrderByAggregateInput
  _min: OrganizationMinOrderByAggregateInput
  _sum: OrganizationSumOrderByAggregateInput
}

input OrganizationCountOrderByAggregateInput {
  id: SortOrder
  githubOrgId: SortOrder
  name: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  description: SortOrder
  twitterHandle: SortOrder
  url: SortOrder
}

input OrganizationAvgOrderByAggregateInput {
  id: SortOrder
  githubOrgId: SortOrder
}

input OrganizationMaxOrderByAggregateInput {
  id: SortOrder
  githubOrgId: SortOrder
  name: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  description: SortOrder
  twitterHandle: SortOrder
  url: SortOrder
}

input OrganizationMinOrderByAggregateInput {
  id: SortOrder
  githubOrgId: SortOrder
  name: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  description: SortOrder
  twitterHandle: SortOrder
  url: SortOrder
}

input OrganizationSumOrderByAggregateInput {
  id: SortOrder
  githubOrgId: SortOrder
}

input OrganizationScalarWhereWithAggregatesInput {
  AND: [OrganizationScalarWhereWithAggregatesInput!]
  OR: [OrganizationScalarWhereWithAggregatesInput!]
  NOT: [OrganizationScalarWhereWithAggregatesInput!]
  id: IntWithAggregatesFilter
  githubOrgId: IntWithAggregatesFilter
  name: StringWithAggregatesFilter
  createdAt: DateTimeWithAggregatesFilter
  updatedAt: DateTimeWithAggregatesFilter
  description: StringNullableWithAggregatesFilter
  twitterHandle: StringNullableWithAggregatesFilter
  url: StringNullableWithAggregatesFilter
}

input ProfileWhereUniqueInput {
  id: Int
  address: String
}

enum ProfileScalarFieldEnum {
  id
  address
  createdAt
  updatedAt
  bio
  bannerImageUrl
  name
  profileImageUrl
  githubHandle
  twitterHandle
  personalSiteUrl
  isVisibleOnLeaderboard
}

type AggregateProfile {
  _count: ProfileCountAggregate
  _avg: ProfileAvgAggregate
  _sum: ProfileSumAggregate
  _min: ProfileMinAggregate
  _max: ProfileMaxAggregate
}

type ProfileCountAggregate {
  id: Int!
  address: Int!
  createdAt: Int!
  updatedAt: Int!
  bio: Int!
  bannerImageUrl: Int!
  name: Int!
  profileImageUrl: Int!
  githubHandle: Int!
  twitterHandle: Int!
  personalSiteUrl: Int!
  isVisibleOnLeaderboard: Int!
  _all: Int!
}

type ProfileAvgAggregate {
  id: Float
}

type ProfileSumAggregate {
  id: Int
}

type ProfileMinAggregate {
  id: Int
  address: String
  createdAt: DateTime
  updatedAt: DateTime
  bio: String
  bannerImageUrl: String
  name: String
  profileImageUrl: String
  githubHandle: String
  twitterHandle: String
  personalSiteUrl: String
  isVisibleOnLeaderboard: Boolean
}

type ProfileMaxAggregate {
  id: Int
  address: String
  createdAt: DateTime
  updatedAt: DateTime
  bio: String
  bannerImageUrl: String
  name: String
  profileImageUrl: String
  githubHandle: String
  twitterHandle: String
  personalSiteUrl: String
  isVisibleOnLeaderboard: Boolean
}

type ProfileGroupBy {
  id: Int!
  address: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  bio: String
  bannerImageUrl: String
  name: String
  profileImageUrl: String
  githubHandle: String
  twitterHandle: String
  personalSiteUrl: String
  isVisibleOnLeaderboard: Boolean!
  _count: ProfileCountAggregate
  _avg: ProfileAvgAggregate
  _sum: ProfileSumAggregate
  _min: ProfileMinAggregate
  _max: ProfileMaxAggregate
}

input ProfileOrderByWithAggregationInput {
  id: SortOrder
  address: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  bio: SortOrder
  bannerImageUrl: SortOrder
  name: SortOrder
  profileImageUrl: SortOrder
  githubHandle: SortOrder
  twitterHandle: SortOrder
  personalSiteUrl: SortOrder
  isVisibleOnLeaderboard: SortOrder
  _count: ProfileCountOrderByAggregateInput
  _avg: ProfileAvgOrderByAggregateInput
  _max: ProfileMaxOrderByAggregateInput
  _min: ProfileMinOrderByAggregateInput
  _sum: ProfileSumOrderByAggregateInput
}

input ProfileCountOrderByAggregateInput {
  id: SortOrder
  address: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  bio: SortOrder
  bannerImageUrl: SortOrder
  name: SortOrder
  profileImageUrl: SortOrder
  githubHandle: SortOrder
  twitterHandle: SortOrder
  personalSiteUrl: SortOrder
  isVisibleOnLeaderboard: SortOrder
}

input ProfileAvgOrderByAggregateInput {
  id: SortOrder
}

input ProfileMaxOrderByAggregateInput {
  id: SortOrder
  address: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  bio: SortOrder
  bannerImageUrl: SortOrder
  name: SortOrder
  profileImageUrl: SortOrder
  githubHandle: SortOrder
  twitterHandle: SortOrder
  personalSiteUrl: SortOrder
  isVisibleOnLeaderboard: SortOrder
}

input ProfileMinOrderByAggregateInput {
  id: SortOrder
  address: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  bio: SortOrder
  bannerImageUrl: SortOrder
  name: SortOrder
  profileImageUrl: SortOrder
  githubHandle: SortOrder
  twitterHandle: SortOrder
  personalSiteUrl: SortOrder
  isVisibleOnLeaderboard: SortOrder
}

input ProfileSumOrderByAggregateInput {
  id: SortOrder
}

input ProfileScalarWhereWithAggregatesInput {
  AND: [ProfileScalarWhereWithAggregatesInput!]
  OR: [ProfileScalarWhereWithAggregatesInput!]
  NOT: [ProfileScalarWhereWithAggregatesInput!]
  id: IntWithAggregatesFilter
  address: StringWithAggregatesFilter
  createdAt: DateTimeWithAggregatesFilter
  updatedAt: DateTimeWithAggregatesFilter
  bio: StringNullableWithAggregatesFilter
  bannerImageUrl: StringNullableWithAggregatesFilter
  name: StringNullableWithAggregatesFilter
  profileImageUrl: StringNullableWithAggregatesFilter
  githubHandle: StringNullableWithAggregatesFilter
  twitterHandle: StringNullableWithAggregatesFilter
  personalSiteUrl: StringNullableWithAggregatesFilter
  isVisibleOnLeaderboard: BoolWithAggregatesFilter
}

input ProjectWhereUniqueInput {
  id: Int
}

enum ProjectScalarFieldEnum {
  id
  createdAt
  updatedAt
}

type AggregateProject {
  _count: ProjectCountAggregate
  _avg: ProjectAvgAggregate
  _sum: ProjectSumAggregate
  _min: ProjectMinAggregate
  _max: ProjectMaxAggregate
}

type ProjectCountAggregate {
  id: Int!
  createdAt: Int!
  updatedAt: Int!
  _all: Int!
}

type ProjectAvgAggregate {
  id: Float
}

type ProjectSumAggregate {
  id: Int
}

type ProjectMinAggregate {
  id: Int
  createdAt: DateTime
  updatedAt: DateTime
}

type ProjectMaxAggregate {
  id: Int
  createdAt: DateTime
  updatedAt: DateTime
}

type ProjectGroupBy {
  id: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  _count: ProjectCountAggregate
  _avg: ProjectAvgAggregate
  _sum: ProjectSumAggregate
  _min: ProjectMinAggregate
  _max: ProjectMaxAggregate
}

input ProjectOrderByWithAggregationInput {
  id: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  _count: ProjectCountOrderByAggregateInput
  _avg: ProjectAvgOrderByAggregateInput
  _max: ProjectMaxOrderByAggregateInput
  _min: ProjectMinOrderByAggregateInput
  _sum: ProjectSumOrderByAggregateInput
}

input ProjectCountOrderByAggregateInput {
  id: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
}

input ProjectAvgOrderByAggregateInput {
  id: SortOrder
}

input ProjectMaxOrderByAggregateInput {
  id: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
}

input ProjectMinOrderByAggregateInput {
  id: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
}

input ProjectSumOrderByAggregateInput {
  id: SortOrder
}

input ProjectScalarWhereWithAggregatesInput {
  AND: [ProjectScalarWhereWithAggregatesInput!]
  OR: [ProjectScalarWhereWithAggregatesInput!]
  NOT: [ProjectScalarWhereWithAggregatesInput!]
  id: IntWithAggregatesFilter
  createdAt: DateTimeWithAggregatesFilter
  updatedAt: DateTimeWithAggregatesFilter
}

type AggregateRepo {
  _count: RepoCountAggregate
  _avg: RepoAvgAggregate
  _sum: RepoSumAggregate
  _min: RepoMinAggregate
  _max: RepoMaxAggregate
}

type RepoCountAggregate {
  id: Int!
  name: Int!
  githubRepoId: Int!
  createdAt: Int!
  updatedAt: Int!
  organizationId: Int!
  projectId: Int!
  lastPRUpdatedAt: Int!
  _all: Int!
}

type RepoAvgAggregate {
  id: Float
  githubRepoId: Float
  organizationId: Float
  projectId: Float
}

type RepoSumAggregate {
  id: Int
  githubRepoId: Int
  organizationId: Int
  projectId: Int
}

type RepoMinAggregate {
  id: Int
  name: String
  githubRepoId: Int
  createdAt: DateTime
  updatedAt: DateTime
  organizationId: Int
  projectId: Int
  lastPRUpdatedAt: DateTime
}

type RepoMaxAggregate {
  id: Int
  name: String
  githubRepoId: Int
  createdAt: DateTime
  updatedAt: DateTime
  organizationId: Int
  projectId: Int
  lastPRUpdatedAt: DateTime
}

type RepoGroupBy {
  id: Int!
  name: String!
  githubRepoId: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  organizationId: Int!
  projectId: Int!
  lastPRUpdatedAt: DateTime!
  _count: RepoCountAggregate
  _avg: RepoAvgAggregate
  _sum: RepoSumAggregate
  _min: RepoMinAggregate
  _max: RepoMaxAggregate
}

input RepoOrderByWithAggregationInput {
  id: SortOrder
  name: SortOrder
  githubRepoId: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  organizationId: SortOrder
  projectId: SortOrder
  lastPRUpdatedAt: SortOrder
  _count: RepoCountOrderByAggregateInput
  _avg: RepoAvgOrderByAggregateInput
  _max: RepoMaxOrderByAggregateInput
  _min: RepoMinOrderByAggregateInput
  _sum: RepoSumOrderByAggregateInput
}

input RepoCountOrderByAggregateInput {
  id: SortOrder
  name: SortOrder
  githubRepoId: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  organizationId: SortOrder
  projectId: SortOrder
  lastPRUpdatedAt: SortOrder
}

input RepoAvgOrderByAggregateInput {
  id: SortOrder
  githubRepoId: SortOrder
  organizationId: SortOrder
  projectId: SortOrder
}

input RepoMaxOrderByAggregateInput {
  id: SortOrder
  name: SortOrder
  githubRepoId: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  organizationId: SortOrder
  projectId: SortOrder
  lastPRUpdatedAt: SortOrder
}

input RepoMinOrderByAggregateInput {
  id: SortOrder
  name: SortOrder
  githubRepoId: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  organizationId: SortOrder
  projectId: SortOrder
  lastPRUpdatedAt: SortOrder
}

input RepoSumOrderByAggregateInput {
  id: SortOrder
  githubRepoId: SortOrder
  organizationId: SortOrder
  projectId: SortOrder
}

input RepoScalarWhereWithAggregatesInput {
  AND: [RepoScalarWhereWithAggregatesInput!]
  OR: [RepoScalarWhereWithAggregatesInput!]
  NOT: [RepoScalarWhereWithAggregatesInput!]
  id: IntWithAggregatesFilter
  name: StringWithAggregatesFilter
  githubRepoId: IntWithAggregatesFilter
  createdAt: DateTimeWithAggregatesFilter
  updatedAt: DateTimeWithAggregatesFilter
  organizationId: IntWithAggregatesFilter
  projectId: IntWithAggregatesFilter
  lastPRUpdatedAt: DateTimeWithAggregatesFilter
}

input UserWhereUniqueInput {
  id: Int
  githubId: Int
}

enum UserScalarFieldEnum {
  id
  githubId
  githubHandle
  createdAt
  updatedAt
}

type AggregateUser {
  _count: UserCountAggregate
  _avg: UserAvgAggregate
  _sum: UserSumAggregate
  _min: UserMinAggregate
  _max: UserMaxAggregate
}

type UserCountAggregate {
  id: Int!
  githubId: Int!
  githubHandle: Int!
  createdAt: Int!
  updatedAt: Int!
  _all: Int!
}

type UserAvgAggregate {
  id: Float
  githubId: Float
}

type UserSumAggregate {
  id: Int
  githubId: Int
}

type UserMinAggregate {
  id: Int
  githubId: Int
  githubHandle: String
  createdAt: DateTime
  updatedAt: DateTime
}

type UserMaxAggregate {
  id: Int
  githubId: Int
  githubHandle: String
  createdAt: DateTime
  updatedAt: DateTime
}

type UserGroupBy {
  id: Int!
  githubId: Int!
  githubHandle: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  _count: UserCountAggregate
  _avg: UserAvgAggregate
  _sum: UserSumAggregate
  _min: UserMinAggregate
  _max: UserMaxAggregate
}

input UserOrderByWithAggregationInput {
  id: SortOrder
  githubId: SortOrder
  githubHandle: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
  _count: UserCountOrderByAggregateInput
  _avg: UserAvgOrderByAggregateInput
  _max: UserMaxOrderByAggregateInput
  _min: UserMinOrderByAggregateInput
  _sum: UserSumOrderByAggregateInput
}

input UserCountOrderByAggregateInput {
  id: SortOrder
  githubId: SortOrder
  githubHandle: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
}

input UserAvgOrderByAggregateInput {
  id: SortOrder
  githubId: SortOrder
}

input UserMaxOrderByAggregateInput {
  id: SortOrder
  githubId: SortOrder
  githubHandle: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
}

input UserMinOrderByAggregateInput {
  id: SortOrder
  githubId: SortOrder
  githubHandle: SortOrder
  createdAt: SortOrder
  updatedAt: SortOrder
}

input UserSumOrderByAggregateInput {
  id: SortOrder
  githubId: SortOrder
}

input UserScalarWhereWithAggregatesInput {
  AND: [UserScalarWhereWithAggregatesInput!]
  OR: [UserScalarWhereWithAggregatesInput!]
  NOT: [UserScalarWhereWithAggregatesInput!]
  id: IntWithAggregatesFilter
  githubId: IntWithAggregatesFilter
  githubHandle: StringWithAggregatesFilter
  createdAt: DateTimeWithAggregatesFilter
  updatedAt: DateTimeWithAggregatesFilter
}

type FullClaimData {
  claim: Claim!
  event: POAPEvent!
}

type POAPEvent {
  id: Float!
  fancy_id: String!
  name: String!
  event_url: String!
  image_url: String!
  country: String!
  city: String!
  description: String!
  year: Float!
  start_date: String!
  end_date: String!
  expiry_date: String!
  supply: Float!
}

type FullGitPOAPEventData {
  gitPOAP: GitPOAP!
  event: POAPEvent!
}

type UserPOAPs {
  totalGitPOAPs: Float!
  totalPOAPs: Float!
  gitPOAPs: [UserGitPOAPData!]!
  poaps: [POAPToken!]!
}

type UserGitPOAPData {
  claim: Claim!
  event: POAPEvent!
}

type POAPToken {
  event: POAPEvent!
  tokenId: String!
  owner: String!
  chain: String!
  created: String!
}

type RepoGitPOAPs {
  totalGitPOAPs: Float!
  gitPOAPs: [FullGitPOAPEventData!]!
}

type GitPOAPWithClaimsCount {
  gitPOAP: GitPOAP!
  event: POAPEvent!
  claimsCount: Float!
}

type UserFeaturedPOAPs {
  gitPOAPs: [UserFeaturedGitPOAPData!]!
  poaps: [POAPToken!]!
}

type UserFeaturedGitPOAPData {
  claim: Claim!
  poap: POAPToken!
}

type Holders {
  totalHolders: Float!
  holders: [Holder!]!
}

type Holder {
  profileId: Float!
  address: String!
  bio: String
  profileImageUrl: String
  twitterHandle: String
  personalSiteUrl: String
  githubHandle: String!
  gitPOAPCount: Float!
}

type RepoData {
  id: Int!
  name: String!
  githubRepoId: Int!
  createdAt: DateTime!
  updatedAt: DateTime!
  organizationId: Int!
  projectId: Int!
  lastPRUpdatedAt: DateTime!
  _count: RepoCount
  organization: Organization!
  GithubPullRequest(
    where: GithubPullRequestWhereInput
    orderBy: [GithubPullRequestOrderByWithRelationInput!]
    cursor: GithubPullRequestWhereUniqueInput
    take: Int
    skip: Int
    distinct: [GithubPullRequestScalarFieldEnum!]
  ): [GithubPullRequest!]!
  project: Project!
  contributorCount: Float!
  gitPOAPCount: Float!
  mintedGitPOAPCount: Float!
}

type OrganizationData {
  id: Int!
  githubOrgId: Int!
  name: String!
  createdAt: DateTime!
  updatedAt: DateTime!
  description: String
  twitterHandle: String
  url: String
  _count: OrganizationCount
  repos(
    where: RepoWhereInput
    orderBy: [RepoOrderByWithRelationInput!]
    cursor: RepoWhereUniqueInput
    take: Int
    skip: Int
    distinct: [RepoScalarFieldEnum!]
  ): [Repo!]!
  contributorCount: Float!
  gitPOAPCount: Float!
  mintedGitPOAPCount: Float!
  repoCount: Float!
}

type NullableProfile {
  id: Float
  address: String!
  ensName: String
  createdAt: DateTime
  updatedAt: DateTime
  bio: String
  bannerImageUrl: String
  name: String
  profileImageUrl: String
  githubHandle: String
  twitterHandle: String
  personalSiteUrl: String
  isVisibleOnLeaderboard: Boolean!
  featuredPOAPs: [FeaturedPOAP!]!
}

type ProfileWithClaimsCount {
  profile: Profile!
  claimsCount: Float!
}

type SearchResults {
  usersByGithubHandle: [User!]!
  profilesByName: [Profile!]!
  profilesByAddress: [Profile!]!
  profileByENS: ProfileWithENS
}

type ProfileWithENS {
  profile: Profile!
  ens: String!
}
