global:
  scrape_interval: 5s # Set the scrape interval to every 5 seconds. Default is every 1 minute.
  evaluation_interval: 10s # Evaluate rules every 5 seconds. The default is every 1 minute.

rule_files:
  - alert.yml

scrape_configs:
  - job_name: services
    metrics_path: /metrics
    static_configs:
      - targets:
          - 'server:8080'
          - 'public-api-server:8081'
          - 'prometheus:9090'
