# This workflow will build and push a new container image to Amazon ECR,
# and then will deploy a new task definition to Amazon ECS, when there is a push to the develop branch.

name: Deploy Public API to Amazon ECS (STAGING)

on:
  push:
    branches:
      - develop

jobs:
  call-deploy-workflow:
    uses: ./.github/workflows/reusable-deploy-public-api-server.yml
    with:
      ECR_REPOSITORY: gitpoap-public-api-staging-server-repository
      ECS_SERVICE: gitpoap-public-api-staging-server-service
      ECS_CLUSTER: gitpoap-public-api-staging-server-cluster
      CONTAINER_NAME: gitpoap-public-api-staging-server
      deploy_environment: staging
      task_definition_tag: '-staging'
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
