# This workflow will build and push a new container image to Amazon ECR,
# and then will deploy a new task definition to Amazon ECS, when there is a push to the main branch.

name: Deploy Public API to Amazon ECS (PROD)

on:
  push:
    branches:
      - main

jobs:
  call-deploy-workflow:
    uses: ./.github/workflows/reusable-deploy-public-api-server.yml
    with:
      ECR_REPOSITORY: gitpoap-public-api-server-repository
      ECS_SERVICE: gitpoap-public-api-server-service
      ECS_CLUSTER: gitpoap-public-api-server-cluster
      CONTAINER_NAME: gitpoap-public-api-server
      deploy_environment: production
      task_definition_tag: ''
    secrets:
      AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
      AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
